//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlHamzaEnterprises.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Attendance
    {
        public int AttendenceID { get; set; }

        [DataType(DataType.Date)]
        public System.DateTime Date { get; set; }
        public bool Present { get; set; }

        [DataType(DataType.Time)]
        public Nullable<System.DateTime> CheckIn { get; set; }
        public int UserID { get; set; }
    
        public virtual User User { get; set; }
    }
}
