//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlHamzaEnterprises.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EmployeeLeave
    {
        public int EmployeeLeaveID { get; set; }

        [DataType(DataType.Date)]
        public System.DateTime DateOfRequest { get; set; }

        [DataType(DataType.Date)]
        public System.DateTime StartDate { get; set; }

        [DataType(DataType.Date)]
        public System.DateTime EndDate { get; set; }
        public string Reason { get; set; }
        public int UserID { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual User User { get; set; }
    }
}
