//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlHamzaEnterprises.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int InvoiceID { get; set; }
        public Nullable<int> Discount { get; set; }
        public int SalesTax { get; set; }
        public int WithHoldingTax { get; set; }
        public int PaidAmount { get; set; }
        public int OrderID { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
