//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlHamzaEnterprises.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Purchase
    {
        public int PurchaseID { get; set; }

        [DataType(DataType.Date)]
        public System.DateTime Date { get; set; }
        public int ProductID { get; set; }
        public double Quantity { get; set; }
        public int DealerID { get; set; }
    
        public virtual Dealer Dealer { get; set; }
        public virtual Product Product { get; set; }
    }
}
